Split SYSTEMD_ENABLED to PRIVILEGED_ENABLED and CGROUP_MOUNT_ENABLED
jboss-set/hera pull request #14
Opened 2022-04-26 11:58 UTC by gaol

This relates to issue: https://issues.redhat.com/browse/SET-422, but if anyone think this deserves a new issue, I can create one for it.

2022-04-26 12:00 UTC, gaol commented
BTW, from https://docs.podman.io/en/latest/markdown/podman-run.1.html#systemd-true-false-always, the `--systemd=true` is the default value.

2022-04-28 08:26 UTC, gaol commented
@rpelisse would you please review ? thanks

2022-04-28 09:38 UTC, rpelisse commented on run.sh
> +    echo "--systemd=true --privileged=true"
@gaol let's be complete about our refactoring! Can you add a system_if_enabled() function? So we'll have one function for each (cgroup, sysd, priv).

2022-04-28 09:39 UTC, rpelisse requested changes
@gaol a few more enhancement, but otherwise it's look good.

2022-04-28 09:39 UTC, rpelisse commented on run.sh
> +            --rm $(add_parent_volume_if_provided) $(privileged_if_enabled) $(cgroup_mount_if_enabled) \
I'll move this to a newline.

2022-04-28 10:17 UTC, gaol commented on run.sh
> +            --rm $(add_parent_volume_if_provided) $(privileged_if_enabled) $(cgroup_mount_if_enabled) \
Moving to a newline will lead to double `\` in case they are **not** defined.

2022-04-28 10:33 UTC, rpelisse approved these changes
@spyrkob LGTM! any comment?

2022-04-28 12:35 UTC, spyrkob commented
LGTM

2022-04-28 13:37 UTC, merged