SET-693 EAP8 Olympus pipelines are having connection issue.
jboss-set/hera pull request #25
Opened 2024-01-29 14:10 UTC by RanabirChakraborty

Issue: https://issues.redhat.com/browse/SET-693

2024-01-29 14:41 UTC, spyrkob commented on run.sh
> +  if [ -d "${TOOLS_DIR}" ]; then
Can you add a note explaining why the network is added when TOOLS_DIR is not specified? Unless this is strictly related I think this should be a separate parameter.

2024-01-29 14:41 UTC, rpelisse requested changes

2024-01-29 14:41 UTC, rpelisse commented on run.sh
> +    return
@RanabirChakraborty I would simply the implementation by doing:
```
  if [ -d "${TOOLS_DIR}" ]; then
        echo 'instance:127.0.0.1'
  fi
```
Two lines less :) 

Also mind the use of simple quote, as this is constant, instead of the double quote (which will led Bash to parse the content for potential variables or cmd substitution).

2024-01-29 14:41 UTC, rpelisse commented on run.sh
> +            --add-host=$(add_instance_host_if_ansible_job) \
That's not going to work! You'll end up with an incomplete command for the non-Ansible job:
`--add-host=`
You should try this before making the PR, you can easily changed a job of Olympus to use your own fork of Hera and this branch.

You need to move the cmd arg into the function:
```
  if [ -d "${TOOLS_DIR}" ]; then
        echo '--add-host=instance:127.0.0.1'
  fi
```
(then the function will return either nothing or the complete command), like `container_user_if_enabled`.

2024-01-29 14:54 UTC, RanabirChakraborty commented on run.sh
> +            --add-host=$(add_instance_host_if_ansible_job) \
okay, I need to check but this worked fine - https://olympus-host.lab.eng.brq2.redhat.com/jenkins/view/eap-8.0.x/job/eap-8.0.x-aligned-core-testsuite/55/consoleFull

2024-01-29 16:55 UTC, rpelisse requested changes

2024-01-29 16:55 UTC, rpelisse commented on run.sh
> +    # TOOLS_DIR does not exist, add instance host
The comment should be "Ansible jobs does NOT have a TOOLS_DIR, so we used that to determine if the job does, or not, require the instance host".

2024-01-29 18:45 UTC, RanabirChakraborty commented
[EAP job](https://olympus-host.lab.eng.brq2.redhat.com/jenkins/view/eap-8.0.x/job/eap-8.0.x-aligned-core-testsuite/57/),
[wildfly ansible job](https://olympus-host.lab.eng.brq2.redhat.com/jenkins/view/Ansible%20CI/job/ansible-ci-wildfly/174/) both passed successfully. Even checked the output looks good to me.

2024-01-30 08:08 UTC, rpelisse approved these changes

2024-01-30 08:09 UTC, merged